model:
    fe:
        arch: resnet10
        pretrained: false
    cls:
        arch: hiernet
        feat_size: 512
    pivot:
        arch: pivot
        dropout_rate: 0.1
data:
    data_path: prepro/data/imagenet
training:
    lmbda: 1
    loss:
        name: cross_entropy
    epoch: 90
    n_workers: 4
    batch_size: 128
    save_interval: 10
    print_interval: 1
    optimizer_main:
        name: sgd
        lr: 0.1
        momentum: 0.9
        weight_decay: 0.0001
    scheduler:
        step_size: 30
        gamma: 0.1
    resume:
        model:
        param_only: true
exp: deep-rtc
